# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43792db78bb32a3669dcbaa1ae20c3a3c3d5f681219349a2a4417033bc6690f3c0c84dd5cb92d9a21543752f932c77d28d639f8d9fb621cc233a61532d7b4aa2

test:
  secret_key_base: 7d134081fbeaddf4cb84aa2c41ad7f2b31f9037a04e81f2716055c91afef33ea0ce7387b81b5a949330e95d6c3047e7ad5834f48498ae41f0749664e0eadba2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
